// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopicMapInfo struct {
	TopicMap             uint64   `protobuf:"varint,1,opt,name=TopicMap,proto3" json:"TopicMap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicMapInfo) Reset()         { *m = TopicMapInfo{} }
func (m *TopicMapInfo) String() string { return proto.CompactTextString(m) }
func (*TopicMapInfo) ProtoMessage()    {}
func (*TopicMapInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_d861d6d34286aa08, []int{0}
}
func (m *TopicMapInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMapInfo.Unmarshal(m, b)
}
func (m *TopicMapInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMapInfo.Marshal(b, m, deterministic)
}
func (dst *TopicMapInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMapInfo.Merge(dst, src)
}
func (m *TopicMapInfo) XXX_Size() int {
	return xxx_messageInfo_TopicMapInfo.Size(m)
}
func (m *TopicMapInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMapInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMapInfo proto.InternalMessageInfo

func (m *TopicMapInfo) GetTopicMap() uint64 {
	if m != nil {
		return m.TopicMap
	}
	return 0
}

type TopicRefList struct {
	ItemIdentifiers      []string `protobuf:"bytes,1,rep,name=item_identifiers,json=itemIdentifiers,proto3" json:"item_identifiers,omitempty"`
	SubjectIndicators    []string `protobuf:"bytes,2,rep,name=subject_indicators,json=subjectIndicators,proto3" json:"subject_indicators,omitempty"`
	SubjectLocators      []string `protobuf:"bytes,3,rep,name=subject_locators,json=subjectLocators,proto3" json:"subject_locators,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicRefList) Reset()         { *m = TopicRefList{} }
func (m *TopicRefList) String() string { return proto.CompactTextString(m) }
func (*TopicRefList) ProtoMessage()    {}
func (*TopicRefList) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_d861d6d34286aa08, []int{1}
}
func (m *TopicRefList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicRefList.Unmarshal(m, b)
}
func (m *TopicRefList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicRefList.Marshal(b, m, deterministic)
}
func (dst *TopicRefList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicRefList.Merge(dst, src)
}
func (m *TopicRefList) XXX_Size() int {
	return xxx_messageInfo_TopicRefList.Size(m)
}
func (m *TopicRefList) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicRefList.DiscardUnknown(m)
}

var xxx_messageInfo_TopicRefList proto.InternalMessageInfo

func (m *TopicRefList) GetItemIdentifiers() []string {
	if m != nil {
		return m.ItemIdentifiers
	}
	return nil
}

func (m *TopicRefList) GetSubjectIndicators() []string {
	if m != nil {
		return m.SubjectIndicators
	}
	return nil
}

func (m *TopicRefList) GetSubjectLocators() []string {
	if m != nil {
		return m.SubjectLocators
	}
	return nil
}

type Name struct {
	Topic                uint64   `protobuf:"varint,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_d861d6d34286aa08, []int{2}
}
func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (dst *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(dst, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetTopic() uint64 {
	if m != nil {
		return m.Topic
	}
	return 0
}

func (m *Name) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Occurrence struct {
	Topic                uint64   `protobuf:"varint,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Occurrence) Reset()         { *m = Occurrence{} }
func (m *Occurrence) String() string { return proto.CompactTextString(m) }
func (*Occurrence) ProtoMessage()    {}
func (*Occurrence) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_d861d6d34286aa08, []int{3}
}
func (m *Occurrence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Occurrence.Unmarshal(m, b)
}
func (m *Occurrence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Occurrence.Marshal(b, m, deterministic)
}
func (dst *Occurrence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Occurrence.Merge(dst, src)
}
func (m *Occurrence) XXX_Size() int {
	return xxx_messageInfo_Occurrence.Size(m)
}
func (m *Occurrence) XXX_DiscardUnknown() {
	xxx_messageInfo_Occurrence.DiscardUnknown(m)
}

var xxx_messageInfo_Occurrence proto.InternalMessageInfo

func (m *Occurrence) GetTopic() uint64 {
	if m != nil {
		return m.Topic
	}
	return 0
}

func (m *Occurrence) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*TopicMapInfo)(nil), "TopicMapInfo")
	proto.RegisterType((*TopicRefList)(nil), "TopicRefList")
	proto.RegisterType((*Name)(nil), "Name")
	proto.RegisterType((*Occurrence)(nil), "Occurrence")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_pb_d861d6d34286aa08) }

var fileDescriptor_pb_d861d6d34286aa08 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x40, 0xc9, 0xee, 0x2a, 0xbb, 0x83, 0xa0, 0x06, 0x0f, 0xc1, 0x53, 0xc9, 0xa9, 0x0a, 0x7a,
	0xd0, 0x8b, 0xbf, 0x50, 0x58, 0x15, 0x82, 0xf7, 0x25, 0xcd, 0x4e, 0x61, 0x64, 0x9b, 0x84, 0x24,
	0xf5, 0x47, 0xfc, 0x61, 0x49, 0x9b, 0xd6, 0xf3, 0x1e, 0xdf, 0x9b, 0x97, 0x61, 0x08, 0x6c, 0x7d,
	0xfb, 0xec, 0x83, 0x4b, 0x4e, 0x3e, 0xc2, 0xd5, 0x97, 0xf3, 0x64, 0xde, 0xb5, 0x6f, 0x6c, 0xe7,
	0xf8, 0x3d, 0x6c, 0x67, 0x16, 0xac, 0x62, 0xf5, 0x46, 0x2d, 0x2c, 0x7f, 0x59, 0x89, 0x15, 0x76,
	0x7b, 0x8a, 0x89, 0x3f, 0xc0, 0x0d, 0x25, 0xec, 0x0f, 0x74, 0x44, 0x9b, 0xa8, 0x23, 0x0c, 0x51,
	0xb0, 0x6a, 0x5d, 0xef, 0xd4, 0x75, 0xf6, 0xcd, 0xbf, 0xe6, 0x4f, 0xc0, 0xe3, 0xd0, 0x7e, 0xa3,
	0x49, 0x07, 0xb2, 0x47, 0x32, 0x3a, 0xb9, 0x10, 0xc5, 0x6a, 0x8c, 0x6f, 0xcb, 0xa4, 0x59, 0x06,
	0x79, 0xf3, 0x9c, 0x9f, 0x5c, 0x89, 0xd7, 0xd3, 0xe6, 0xe2, 0xf7, 0x45, 0xcb, 0x17, 0xd8, 0x7c,
	0xe8, 0x1e, 0xf9, 0x1d, 0x5c, 0xa4, 0x7c, 0x5c, 0x39, 0x7b, 0x82, 0x6c, 0x7f, 0xf4, 0x69, 0x40,
	0xb1, 0xaa, 0x58, 0xbd, 0x53, 0x13, 0xc8, 0x37, 0x80, 0x4f, 0x63, 0x86, 0x10, 0xd0, 0x9a, 0xb3,
	0x5e, 0xb6, 0x97, 0xe3, 0xb7, 0xbd, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xb2, 0xee, 0x90,
	0x42, 0x01, 0x00, 0x00,
}
