#!/bin/bash
set -e

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against -- || ( echo "found whitespace errors" ; exit 1 )

gopkgs="$(go list ./... | grep -v 'vendor|third_party')"

gofmt -d . 2>&1 || ( echo "gofmt found diffs" ; exit 1 )

go test -timeout 30s -short ${gopkgs} || ( echo "go test failed" ; exit 1 )
