#!/bin/bash
set -e

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against -- || ( echo "found whitespace errors" ; exit 1 )

# Find relevant packages.
gopkgs="$(go list ./... | grep -v 'vendor|third_party')"
dartpkgs="$(ls -d ./packages/* )"

# Fail if automatic formatting would change anything
gofmt -d . 2>&1 || ( echo "gofmt would change some files" ; exit 1 )
flutter format --dry-run --set-exit-if-changed ./packages > /dev/null || ( echo "flutter format would change some files" ; exit 1 )

# Run tests, but quickly.
#go test -timeout 30s -short ${gopkgs} || ( echo "go test failed" ; exit 1 )
