// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopicMapInfo struct {
	// topic_map is the kv.Entity that identifies this topic map.
	TopicMap uint64 `protobuf:"varint,1,opt,name=topic_map,json=topicMap,proto3" json:"topic_map,omitempty"`
	// modified_unix_seconds is the time this topic map was last modified, in
	// seconds since the Unix epoch.
	ModifiedUnixSeconds int64 `protobuf:"varint,2,opt,name=modified_unix_seconds,json=modifiedUnixSeconds,proto3" json:"modified_unix_seconds,omitempty"`
	// in_trash is true if and only if this topic map has been moved to the trash
	// bin. If true, then modified_unix_seconds is also the time that this topic
	// map was deleted.
	InTrash              bool     `protobuf:"varint,3,opt,name=in_trash,json=inTrash,proto3" json:"in_trash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicMapInfo) Reset()         { *m = TopicMapInfo{} }
func (m *TopicMapInfo) String() string { return proto.CompactTextString(m) }
func (*TopicMapInfo) ProtoMessage()    {}
func (*TopicMapInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_68658ff278b69293, []int{0}
}
func (m *TopicMapInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMapInfo.Unmarshal(m, b)
}
func (m *TopicMapInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMapInfo.Marshal(b, m, deterministic)
}
func (dst *TopicMapInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMapInfo.Merge(dst, src)
}
func (m *TopicMapInfo) XXX_Size() int {
	return xxx_messageInfo_TopicMapInfo.Size(m)
}
func (m *TopicMapInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMapInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMapInfo proto.InternalMessageInfo

func (m *TopicMapInfo) GetTopicMap() uint64 {
	if m != nil {
		return m.TopicMap
	}
	return 0
}

func (m *TopicMapInfo) GetModifiedUnixSeconds() int64 {
	if m != nil {
		return m.ModifiedUnixSeconds
	}
	return 0
}

func (m *TopicMapInfo) GetInTrash() bool {
	if m != nil {
		return m.InTrash
	}
	return false
}

type TopicRefList struct {
	ItemIdentifiers      []string `protobuf:"bytes,1,rep,name=item_identifiers,json=itemIdentifiers,proto3" json:"item_identifiers,omitempty"`
	SubjectIndicators    []string `protobuf:"bytes,2,rep,name=subject_indicators,json=subjectIndicators,proto3" json:"subject_indicators,omitempty"`
	SubjectLocators      []string `protobuf:"bytes,3,rep,name=subject_locators,json=subjectLocators,proto3" json:"subject_locators,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicRefList) Reset()         { *m = TopicRefList{} }
func (m *TopicRefList) String() string { return proto.CompactTextString(m) }
func (*TopicRefList) ProtoMessage()    {}
func (*TopicRefList) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_68658ff278b69293, []int{1}
}
func (m *TopicRefList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicRefList.Unmarshal(m, b)
}
func (m *TopicRefList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicRefList.Marshal(b, m, deterministic)
}
func (dst *TopicRefList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicRefList.Merge(dst, src)
}
func (m *TopicRefList) XXX_Size() int {
	return xxx_messageInfo_TopicRefList.Size(m)
}
func (m *TopicRefList) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicRefList.DiscardUnknown(m)
}

var xxx_messageInfo_TopicRefList proto.InternalMessageInfo

func (m *TopicRefList) GetItemIdentifiers() []string {
	if m != nil {
		return m.ItemIdentifiers
	}
	return nil
}

func (m *TopicRefList) GetSubjectIndicators() []string {
	if m != nil {
		return m.SubjectIndicators
	}
	return nil
}

func (m *TopicRefList) GetSubjectLocators() []string {
	if m != nil {
		return m.SubjectLocators
	}
	return nil
}

type Name struct {
	Topic                uint64   `protobuf:"varint,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_68658ff278b69293, []int{2}
}
func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (dst *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(dst, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetTopic() uint64 {
	if m != nil {
		return m.Topic
	}
	return 0
}

func (m *Name) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Occurrence struct {
	Topic                uint64   `protobuf:"varint,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Occurrence) Reset()         { *m = Occurrence{} }
func (m *Occurrence) String() string { return proto.CompactTextString(m) }
func (*Occurrence) ProtoMessage()    {}
func (*Occurrence) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_68658ff278b69293, []int{3}
}
func (m *Occurrence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Occurrence.Unmarshal(m, b)
}
func (m *Occurrence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Occurrence.Marshal(b, m, deterministic)
}
func (dst *Occurrence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Occurrence.Merge(dst, src)
}
func (m *Occurrence) XXX_Size() int {
	return xxx_messageInfo_Occurrence.Size(m)
}
func (m *Occurrence) XXX_DiscardUnknown() {
	xxx_messageInfo_Occurrence.DiscardUnknown(m)
}

var xxx_messageInfo_Occurrence proto.InternalMessageInfo

func (m *Occurrence) GetTopic() uint64 {
	if m != nil {
		return m.Topic
	}
	return 0
}

func (m *Occurrence) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*TopicMapInfo)(nil), "TopicMapInfo")
	proto.RegisterType((*TopicRefList)(nil), "TopicRefList")
	proto.RegisterType((*Name)(nil), "Name")
	proto.RegisterType((*Occurrence)(nil), "Occurrence")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_pb_68658ff278b69293) }

var fileDescriptor_pb_68658ff278b69293 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4f, 0xc4, 0x20,
	0x10, 0x85, 0x83, 0x5d, 0xb5, 0x3b, 0x31, 0x51, 0x51, 0x93, 0x1a, 0x2f, 0x4d, 0x4f, 0xf5, 0xa0,
	0x87, 0xf5, 0xe2, 0x5f, 0x68, 0xb2, 0x6a, 0x82, 0xeb, 0x99, 0x50, 0x4a, 0xe3, 0x98, 0x2d, 0x10,
	0xa0, 0x66, 0xe3, 0xdf, 0xf0, 0x0f, 0x1b, 0x5a, 0x56, 0xcf, 0x1e, 0xdf, 0xf7, 0x1e, 0x0f, 0x86,
	0x81, 0xdc, 0xb6, 0xf7, 0xd6, 0x99, 0x60, 0xaa, 0x2f, 0x38, 0xd9, 0x18, 0x8b, 0xf2, 0x49, 0xd8,
	0x46, 0xf7, 0x86, 0xde, 0xc0, 0x32, 0x44, 0xcd, 0x07, 0x61, 0x0b, 0x52, 0x92, 0x7a, 0xc1, 0xf2,
	0x90, 0x02, 0x74, 0x05, 0x57, 0x83, 0xe9, 0xb0, 0x47, 0xd5, 0xf1, 0x51, 0xe3, 0x8e, 0x7b, 0x25,
	0x8d, 0xee, 0x7c, 0x71, 0x50, 0x92, 0x3a, 0x63, 0x17, 0x7b, 0xf3, 0x4d, 0xe3, 0xee, 0x75, 0xb6,
	0xe8, 0x35, 0xe4, 0xa8, 0x79, 0x70, 0xc2, 0xbf, 0x17, 0x59, 0x49, 0xea, 0x9c, 0x1d, 0xa3, 0xde,
	0x44, 0x59, 0x7d, 0x93, 0x74, 0x39, 0x53, 0xfd, 0x1a, 0x7d, 0xa0, 0xb7, 0x70, 0x86, 0x41, 0x0d,
	0x1c, 0x3b, 0xa5, 0x43, 0x6c, 0x72, 0xbe, 0x20, 0x65, 0x56, 0x2f, 0xd9, 0x69, 0xe4, 0xcd, 0x1f,
	0xa6, 0x77, 0x40, 0xfd, 0xd8, 0x7e, 0x28, 0x19, 0x38, 0xea, 0x0e, 0xa5, 0x08, 0xc6, 0xc5, 0x77,
	0xc4, 0xf0, 0x79, 0x72, 0x9a, 0x5f, 0x23, 0x36, 0xef, 0xe3, 0x5b, 0x93, 0xc2, 0xd9, 0xdc, 0x9c,
	0xf8, 0x3a, 0xe1, 0x6a, 0x05, 0x8b, 0x67, 0x31, 0x28, 0x7a, 0x09, 0x87, 0xd3, 0xe0, 0xe9, 0x17,
	0x66, 0x11, 0xe9, 0xa7, 0xd8, 0x8e, 0x6a, 0x1a, 0x79, 0xc9, 0x66, 0x51, 0x3d, 0x02, 0xbc, 0x48,
	0x39, 0x3a, 0xa7, 0xb4, 0xfc, 0xd7, 0xc9, 0xf6, 0x68, 0x5a, 0xc3, 0xc3, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x41, 0x36, 0xd2, 0xfa, 0x92, 0x01, 0x00, 0x00,
}
