// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemType int32

const (
	ItemType_UnspecifiedItem ItemType = 0
	ItemType_LibraryItem     ItemType = 1
	ItemType_TopicMapItem    ItemType = 2
	ItemType_TopicItem       ItemType = 3
	ItemType_NameItem        ItemType = 4
	// VariantItem = 5;
	ItemType_OccurrenceItem ItemType = 6
)

var ItemType_name = map[int32]string{
	0: "UnspecifiedItem",
	1: "LibraryItem",
	2: "TopicMapItem",
	3: "TopicItem",
	4: "NameItem",
	6: "OccurrenceItem",
}
var ItemType_value = map[string]int32{
	"UnspecifiedItem": 0,
	"LibraryItem":     1,
	"TopicMapItem":    2,
	"TopicItem":       3,
	"NameItem":        4,
	"OccurrenceItem":  6,
}

func (x ItemType) String() string {
	return proto.EnumName(ItemType_name, int32(x))
}
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{0}
}

type Orderable int32

const (
	Orderable_OrderableUnspecified Orderable = 0
	Orderable_OrderableNames       Orderable = 1
	Orderable_OrderableOccurrences Orderable = 2
)

var Orderable_name = map[int32]string{
	0: "OrderableUnspecified",
	1: "OrderableNames",
	2: "OrderableOccurrences",
}
var Orderable_value = map[string]int32{
	"OrderableUnspecified": 0,
	"OrderableNames":       1,
	"OrderableOccurrences": 2,
}

func (x Orderable) String() string {
	return proto.EnumName(Orderable_name, int32(x))
}
func (Orderable) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{1}
}

type Library struct {
	TopicMapIds          []uint64 `protobuf:"varint,1,rep,packed,name=topic_map_ids,json=topicMapIds,proto3" json:"topic_map_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Library) Reset()         { *m = Library{} }
func (m *Library) String() string { return proto.CompactTextString(m) }
func (*Library) ProtoMessage()    {}
func (*Library) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{0}
}
func (m *Library) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Library.Unmarshal(m, b)
}
func (m *Library) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Library.Marshal(b, m, deterministic)
}
func (dst *Library) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Library.Merge(dst, src)
}
func (m *Library) XXX_Size() int {
	return xxx_messageInfo_Library.Size(m)
}
func (m *Library) XXX_DiscardUnknown() {
	xxx_messageInfo_Library.DiscardUnknown(m)
}

var xxx_messageInfo_Library proto.InternalMessageInfo

func (m *Library) GetTopicMapIds() []uint64 {
	if m != nil {
		return m.TopicMapIds
	}
	return nil
}

type TopicMap struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                *Topic   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	InTrash              bool     `protobuf:"varint,3,opt,name=in_trash,json=inTrash,proto3" json:"in_trash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicMap) Reset()         { *m = TopicMap{} }
func (m *TopicMap) String() string { return proto.CompactTextString(m) }
func (*TopicMap) ProtoMessage()    {}
func (*TopicMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{1}
}
func (m *TopicMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMap.Unmarshal(m, b)
}
func (m *TopicMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMap.Marshal(b, m, deterministic)
}
func (dst *TopicMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMap.Merge(dst, src)
}
func (m *TopicMap) XXX_Size() int {
	return xxx_messageInfo_TopicMap.Size(m)
}
func (m *TopicMap) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMap.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMap proto.InternalMessageInfo

func (m *TopicMap) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TopicMap) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *TopicMap) GetInTrash() bool {
	if m != nil {
		return m.InTrash
	}
	return false
}

type Topic struct {
	TopicMapId           uint64        `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	Id                   uint64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Names                []*Name       `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	Occurrences          []*Occurrence `protobuf:"bytes,4,rep,name=occurrences,proto3" json:"occurrences,omitempty"`
	NameIds              []uint64      `protobuf:"varint,5,rep,packed,name=name_ids,json=nameIds,proto3" json:"name_ids,omitempty"`
	OccurrenceIds        []uint64      `protobuf:"varint,6,rep,packed,name=occurrence_ids,json=occurrenceIds,proto3" json:"occurrence_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{2}
}
func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (dst *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(dst, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *Topic) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Topic) GetNames() []*Name {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Topic) GetOccurrences() []*Occurrence {
	if m != nil {
		return m.Occurrences
	}
	return nil
}

func (m *Topic) GetNameIds() []uint64 {
	if m != nil {
		return m.NameIds
	}
	return nil
}

func (m *Topic) GetOccurrenceIds() []uint64 {
	if m != nil {
		return m.OccurrenceIds
	}
	return nil
}

type Name struct {
	TopicMapId           uint64   `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	ParentId             uint64   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{3}
}
func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (dst *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(dst, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *Name) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Name) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Name) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Occurrence struct {
	TopicMapId           uint64   `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	ParentId             uint64   `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Id                   uint64   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Occurrence) Reset()         { *m = Occurrence{} }
func (m *Occurrence) String() string { return proto.CompactTextString(m) }
func (*Occurrence) ProtoMessage()    {}
func (*Occurrence) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{4}
}
func (m *Occurrence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Occurrence.Unmarshal(m, b)
}
func (m *Occurrence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Occurrence.Marshal(b, m, deterministic)
}
func (dst *Occurrence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Occurrence.Merge(dst, src)
}
func (m *Occurrence) XXX_Size() int {
	return xxx_messageInfo_Occurrence.Size(m)
}
func (m *Occurrence) XXX_DiscardUnknown() {
	xxx_messageInfo_Occurrence.DiscardUnknown(m)
}

var xxx_messageInfo_Occurrence proto.InternalMessageInfo

func (m *Occurrence) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *Occurrence) GetParentId() uint64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Occurrence) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Occurrence) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Item struct {
	// Types that are valid to be assigned to Specific:
	//	*Item_Library
	//	*Item_TopicMap
	//	*Item_Topic
	//	*Item_Name
	//	*Item_Occurrence
	Specific             isItem_Specific `protobuf_oneof:"specific"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{5}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

type isItem_Specific interface {
	isItem_Specific()
}

type Item_Library struct {
	Library *Library `protobuf:"bytes,1,opt,name=library,proto3,oneof"`
}

type Item_TopicMap struct {
	TopicMap *TopicMap `protobuf:"bytes,2,opt,name=topic_map,json=topicMap,proto3,oneof"`
}

type Item_Topic struct {
	Topic *Topic `protobuf:"bytes,3,opt,name=topic,proto3,oneof"`
}

type Item_Name struct {
	Name *Name `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}

type Item_Occurrence struct {
	Occurrence *Occurrence `protobuf:"bytes,6,opt,name=occurrence,proto3,oneof"`
}

func (*Item_Library) isItem_Specific() {}

func (*Item_TopicMap) isItem_Specific() {}

func (*Item_Topic) isItem_Specific() {}

func (*Item_Name) isItem_Specific() {}

func (*Item_Occurrence) isItem_Specific() {}

func (m *Item) GetSpecific() isItem_Specific {
	if m != nil {
		return m.Specific
	}
	return nil
}

func (m *Item) GetLibrary() *Library {
	if x, ok := m.GetSpecific().(*Item_Library); ok {
		return x.Library
	}
	return nil
}

func (m *Item) GetTopicMap() *TopicMap {
	if x, ok := m.GetSpecific().(*Item_TopicMap); ok {
		return x.TopicMap
	}
	return nil
}

func (m *Item) GetTopic() *Topic {
	if x, ok := m.GetSpecific().(*Item_Topic); ok {
		return x.Topic
	}
	return nil
}

func (m *Item) GetName() *Name {
	if x, ok := m.GetSpecific().(*Item_Name); ok {
		return x.Name
	}
	return nil
}

func (m *Item) GetOccurrence() *Occurrence {
	if x, ok := m.GetSpecific().(*Item_Occurrence); ok {
		return x.Occurrence
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Item) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Item_OneofMarshaler, _Item_OneofUnmarshaler, _Item_OneofSizer, []interface{}{
		(*Item_Library)(nil),
		(*Item_TopicMap)(nil),
		(*Item_Topic)(nil),
		(*Item_Name)(nil),
		(*Item_Occurrence)(nil),
	}
}

func _Item_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Item)
	// specific
	switch x := m.Specific.(type) {
	case *Item_Library:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Library); err != nil {
			return err
		}
	case *Item_TopicMap:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TopicMap); err != nil {
			return err
		}
	case *Item_Topic:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Topic); err != nil {
			return err
		}
	case *Item_Name:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Name); err != nil {
			return err
		}
	case *Item_Occurrence:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Occurrence); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Item.Specific has unexpected type %T", x)
	}
	return nil
}

func _Item_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Item)
	switch tag {
	case 1: // specific.library
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Library)
		err := b.DecodeMessage(msg)
		m.Specific = &Item_Library{msg}
		return true, err
	case 2: // specific.topic_map
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TopicMap)
		err := b.DecodeMessage(msg)
		m.Specific = &Item_TopicMap{msg}
		return true, err
	case 3: // specific.topic
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Topic)
		err := b.DecodeMessage(msg)
		m.Specific = &Item_Topic{msg}
		return true, err
	case 4: // specific.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Name)
		err := b.DecodeMessage(msg)
		m.Specific = &Item_Name{msg}
		return true, err
	case 6: // specific.occurrence
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Occurrence)
		err := b.DecodeMessage(msg)
		m.Specific = &Item_Occurrence{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Item_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Item)
	// specific
	switch x := m.Specific.(type) {
	case *Item_Library:
		s := proto.Size(x.Library)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Item_TopicMap:
		s := proto.Size(x.TopicMap)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Item_Topic:
		s := proto.Size(x.Topic)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Item_Name:
		s := proto.Size(x.Name)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Item_Occurrence:
		s := proto.Size(x.Occurrence)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LoadRequest struct {
	// If necessary, identifies the topic map that contains the item to load.
	TopicMapId uint64 `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	// Identifies the item to load.
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Specifies which type of item to load. For items that can be reified by a
	// topic, there are multiple valid types for the same id.
	ItemType             ItemType `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3,enum=ItemType" json:"item_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{6}
}
func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (dst *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(dst, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *LoadRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoadRequest) GetItemType() ItemType {
	if m != nil {
		return m.ItemType
	}
	return ItemType_UnspecifiedItem
}

type LoadResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{7}
}
func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (dst *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(dst, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type SearchRequest struct {
	TopicMapIds          []uint64 `protobuf:"varint,1,rep,packed,name=topic_map_ids,json=topicMapIds,proto3" json:"topic_map_ids,omitempty"`
	Tmql                 string   `protobuf:"bytes,2,opt,name=tmql,proto3" json:"tmql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{8}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (dst *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(dst, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetTopicMapIds() []uint64 {
	if m != nil {
		return m.TopicMapIds
	}
	return nil
}

func (m *SearchRequest) GetTmql() string {
	if m != nil {
		return m.Tmql
	}
	return ""
}

type SearchResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{9}
}
func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (dst *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(dst, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SearchResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SearchResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type QueryRequest struct {
	LoadRequests         []*LoadRequest   `protobuf:"bytes,1,rep,name=load_requests,json=loadRequests,proto3" json:"load_requests,omitempty"`
	SearchRequests       []*SearchRequest `protobuf:"bytes,2,rep,name=search_requests,json=searchRequests,proto3" json:"search_requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{10}
}
func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (dst *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(dst, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetLoadRequests() []*LoadRequest {
	if m != nil {
		return m.LoadRequests
	}
	return nil
}

func (m *QueryRequest) GetSearchRequests() []*SearchRequest {
	if m != nil {
		return m.SearchRequests
	}
	return nil
}

type QueryResponse struct {
	LoadResponses        []*LoadResponse   `protobuf:"bytes,1,rep,name=load_responses,json=loadResponses,proto3" json:"load_responses,omitempty"`
	SearchResponses      []*SearchResponse `protobuf:"bytes,2,rep,name=search_responses,json=searchResponses,proto3" json:"search_responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{11}
}
func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (dst *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(dst, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetLoadResponses() []*LoadResponse {
	if m != nil {
		return m.LoadResponses
	}
	return nil
}

func (m *QueryResponse) GetSearchResponses() []*SearchResponse {
	if m != nil {
		return m.SearchResponses
	}
	return nil
}

type CreationRequest struct {
	// May be zero only if type is TopicMap.
	TopicMapId uint64 `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	// May be zero only if type is TopicMap.
	Parent uint64 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// Must not be Library.
	ItemType             ItemType `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3,enum=ItemType" json:"item_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreationRequest) Reset()         { *m = CreationRequest{} }
func (m *CreationRequest) String() string { return proto.CompactTextString(m) }
func (*CreationRequest) ProtoMessage()    {}
func (*CreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{12}
}
func (m *CreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreationRequest.Unmarshal(m, b)
}
func (m *CreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreationRequest.Marshal(b, m, deterministic)
}
func (dst *CreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationRequest.Merge(dst, src)
}
func (m *CreationRequest) XXX_Size() int {
	return xxx_messageInfo_CreationRequest.Size(m)
}
func (m *CreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreationRequest proto.InternalMessageInfo

func (m *CreationRequest) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *CreationRequest) GetParent() uint64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *CreationRequest) GetItemType() ItemType {
	if m != nil {
		return m.ItemType
	}
	return ItemType_UnspecifiedItem
}

type UpdateOrderRequest struct {
	TopicMapId           uint64    `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	Id                   uint64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Orderable            Orderable `protobuf:"varint,4,opt,name=orderable,proto3,enum=Orderable" json:"orderable,omitempty"`
	SrcIndices           []uint32  `protobuf:"varint,5,rep,packed,name=src_indices,json=srcIndices,proto3" json:"src_indices,omitempty"`
	DstIndices           []uint32  `protobuf:"varint,6,rep,packed,name=dst_indices,json=dstIndices,proto3" json:"dst_indices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateOrderRequest) Reset()         { *m = UpdateOrderRequest{} }
func (m *UpdateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderRequest) ProtoMessage()    {}
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{13}
}
func (m *UpdateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderRequest.Unmarshal(m, b)
}
func (m *UpdateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderRequest.Merge(dst, src)
}
func (m *UpdateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderRequest.Size(m)
}
func (m *UpdateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderRequest proto.InternalMessageInfo

func (m *UpdateOrderRequest) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *UpdateOrderRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateOrderRequest) GetOrderable() Orderable {
	if m != nil {
		return m.Orderable
	}
	return Orderable_OrderableUnspecified
}

func (m *UpdateOrderRequest) GetSrcIndices() []uint32 {
	if m != nil {
		return m.SrcIndices
	}
	return nil
}

func (m *UpdateOrderRequest) GetDstIndices() []uint32 {
	if m != nil {
		return m.DstIndices
	}
	return nil
}

type UpdateValueRequest struct {
	TopicMapId           uint64   `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ItemType             ItemType `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3,enum=ItemType" json:"item_type,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateValueRequest) Reset()         { *m = UpdateValueRequest{} }
func (m *UpdateValueRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateValueRequest) ProtoMessage()    {}
func (*UpdateValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{14}
}
func (m *UpdateValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateValueRequest.Unmarshal(m, b)
}
func (m *UpdateValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateValueRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateValueRequest.Merge(dst, src)
}
func (m *UpdateValueRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateValueRequest.Size(m)
}
func (m *UpdateValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateValueRequest proto.InternalMessageInfo

func (m *UpdateValueRequest) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *UpdateValueRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateValueRequest) GetItemType() ItemType {
	if m != nil {
		return m.ItemType
	}
	return ItemType_UnspecifiedItem
}

func (m *UpdateValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UpdateResponse struct {
	TopicMapId           uint64   `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Item                 *Item    `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{15}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *UpdateResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type DeletionRequest struct {
	TopicMapId           uint64   `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ItemType             ItemType `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3,enum=ItemType" json:"item_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletionRequest) Reset()         { *m = DeletionRequest{} }
func (m *DeletionRequest) String() string { return proto.CompactTextString(m) }
func (*DeletionRequest) ProtoMessage()    {}
func (*DeletionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{16}
}
func (m *DeletionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletionRequest.Unmarshal(m, b)
}
func (m *DeletionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletionRequest.Marshal(b, m, deterministic)
}
func (dst *DeletionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletionRequest.Merge(dst, src)
}
func (m *DeletionRequest) XXX_Size() int {
	return xxx_messageInfo_DeletionRequest.Size(m)
}
func (m *DeletionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletionRequest proto.InternalMessageInfo

func (m *DeletionRequest) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *DeletionRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeletionRequest) GetItemType() ItemType {
	if m != nil {
		return m.ItemType
	}
	return ItemType_UnspecifiedItem
}

type DeletionResponse struct {
	TopicMapId           uint64   `protobuf:"varint,1,opt,name=topic_map_id,json=topicMapId,proto3" json:"topic_map_id,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ItemType             ItemType `protobuf:"varint,3,opt,name=item_type,json=itemType,proto3,enum=ItemType" json:"item_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletionResponse) Reset()         { *m = DeletionResponse{} }
func (m *DeletionResponse) String() string { return proto.CompactTextString(m) }
func (*DeletionResponse) ProtoMessage()    {}
func (*DeletionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{17}
}
func (m *DeletionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletionResponse.Unmarshal(m, b)
}
func (m *DeletionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletionResponse.Marshal(b, m, deterministic)
}
func (dst *DeletionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletionResponse.Merge(dst, src)
}
func (m *DeletionResponse) XXX_Size() int {
	return xxx_messageInfo_DeletionResponse.Size(m)
}
func (m *DeletionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletionResponse proto.InternalMessageInfo

func (m *DeletionResponse) GetTopicMapId() uint64 {
	if m != nil {
		return m.TopicMapId
	}
	return 0
}

func (m *DeletionResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeletionResponse) GetItemType() ItemType {
	if m != nil {
		return m.ItemType
	}
	return ItemType_UnspecifiedItem
}

type MutationRequest struct {
	CreationRequests     []*CreationRequest    `protobuf:"bytes,1,rep,name=creation_requests,json=creationRequests,proto3" json:"creation_requests,omitempty"`
	UpdateOrderRequests  []*UpdateOrderRequest `protobuf:"bytes,2,rep,name=update_order_requests,json=updateOrderRequests,proto3" json:"update_order_requests,omitempty"`
	UpdateValueRequests  []*UpdateValueRequest `protobuf:"bytes,3,rep,name=update_value_requests,json=updateValueRequests,proto3" json:"update_value_requests,omitempty"`
	DeletionRequests     []*DeletionRequest    `protobuf:"bytes,4,rep,name=deletion_requests,json=deletionRequests,proto3" json:"deletion_requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MutationRequest) Reset()         { *m = MutationRequest{} }
func (m *MutationRequest) String() string { return proto.CompactTextString(m) }
func (*MutationRequest) ProtoMessage()    {}
func (*MutationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{18}
}
func (m *MutationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationRequest.Unmarshal(m, b)
}
func (m *MutationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationRequest.Marshal(b, m, deterministic)
}
func (dst *MutationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationRequest.Merge(dst, src)
}
func (m *MutationRequest) XXX_Size() int {
	return xxx_messageInfo_MutationRequest.Size(m)
}
func (m *MutationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutationRequest proto.InternalMessageInfo

func (m *MutationRequest) GetCreationRequests() []*CreationRequest {
	if m != nil {
		return m.CreationRequests
	}
	return nil
}

func (m *MutationRequest) GetUpdateOrderRequests() []*UpdateOrderRequest {
	if m != nil {
		return m.UpdateOrderRequests
	}
	return nil
}

func (m *MutationRequest) GetUpdateValueRequests() []*UpdateValueRequest {
	if m != nil {
		return m.UpdateValueRequests
	}
	return nil
}

func (m *MutationRequest) GetDeletionRequests() []*DeletionRequest {
	if m != nil {
		return m.DeletionRequests
	}
	return nil
}

type MutationResponse struct {
	CreationResponses    []*UpdateResponse   `protobuf:"bytes,1,rep,name=creation_responses,json=creationResponses,proto3" json:"creation_responses,omitempty"`
	UpdateOrderResponses []*UpdateResponse   `protobuf:"bytes,2,rep,name=update_order_responses,json=updateOrderResponses,proto3" json:"update_order_responses,omitempty"`
	UpdateValueResponses []*UpdateResponse   `protobuf:"bytes,3,rep,name=update_value_responses,json=updateValueResponses,proto3" json:"update_value_responses,omitempty"`
	DeletionResponses    []*DeletionResponse `protobuf:"bytes,4,rep,name=deletion_responses,json=deletionResponses,proto3" json:"deletion_responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MutationResponse) Reset()         { *m = MutationResponse{} }
func (m *MutationResponse) String() string { return proto.CompactTextString(m) }
func (*MutationResponse) ProtoMessage()    {}
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pb_5320433e7bb21379, []int{19}
}
func (m *MutationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationResponse.Unmarshal(m, b)
}
func (m *MutationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationResponse.Marshal(b, m, deterministic)
}
func (dst *MutationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationResponse.Merge(dst, src)
}
func (m *MutationResponse) XXX_Size() int {
	return xxx_messageInfo_MutationResponse.Size(m)
}
func (m *MutationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutationResponse proto.InternalMessageInfo

func (m *MutationResponse) GetCreationResponses() []*UpdateResponse {
	if m != nil {
		return m.CreationResponses
	}
	return nil
}

func (m *MutationResponse) GetUpdateOrderResponses() []*UpdateResponse {
	if m != nil {
		return m.UpdateOrderResponses
	}
	return nil
}

func (m *MutationResponse) GetUpdateValueResponses() []*UpdateResponse {
	if m != nil {
		return m.UpdateValueResponses
	}
	return nil
}

func (m *MutationResponse) GetDeletionResponses() []*DeletionResponse {
	if m != nil {
		return m.DeletionResponses
	}
	return nil
}

func init() {
	proto.RegisterType((*Library)(nil), "Library")
	proto.RegisterType((*TopicMap)(nil), "TopicMap")
	proto.RegisterType((*Topic)(nil), "Topic")
	proto.RegisterType((*Name)(nil), "Name")
	proto.RegisterType((*Occurrence)(nil), "Occurrence")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*LoadRequest)(nil), "LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "LoadResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
	proto.RegisterType((*CreationRequest)(nil), "CreationRequest")
	proto.RegisterType((*UpdateOrderRequest)(nil), "UpdateOrderRequest")
	proto.RegisterType((*UpdateValueRequest)(nil), "UpdateValueRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*DeletionRequest)(nil), "DeletionRequest")
	proto.RegisterType((*DeletionResponse)(nil), "DeletionResponse")
	proto.RegisterType((*MutationRequest)(nil), "MutationRequest")
	proto.RegisterType((*MutationResponse)(nil), "MutationResponse")
	proto.RegisterEnum("ItemType", ItemType_name, ItemType_value)
	proto.RegisterEnum("Orderable", Orderable_name, Orderable_value)
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_pb_5320433e7bb21379) }

var fileDescriptor_pb_5320433e7bb21379 = []byte{
	// 979 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xeb, 0x6a, 0xec, 0x54,
	0x14, 0x9e, 0x4c, 0x32, 0xd3, 0x64, 0xcd, 0xe4, 0xd2, 0xdd, 0x5a, 0x72, 0xa8, 0xe8, 0x10, 0x54,
	0xc6, 0x03, 0x0d, 0x38, 0x0a, 0x82, 0xa0, 0x88, 0x17, 0xce, 0x14, 0xce, 0xb1, 0xb8, 0xdb, 0xe3,
	0x1f, 0x91, 0x21, 0x4d, 0x76, 0x3d, 0xe1, 0x64, 0x92, 0x34, 0x3b, 0x23, 0xd4, 0x7f, 0x82, 0x2f,
	0xa2, 0x8f, 0xe0, 0x4b, 0xf8, 0xcf, 0x67, 0x92, 0x7d, 0xcb, 0xad, 0x28, 0xd3, 0x82, 0xfe, 0x9b,
	0xf5, 0xed, 0xb5, 0xd7, 0xe5, 0x5b, 0xdf, 0x5e, 0x13, 0x30, 0xcb, 0xeb, 0xb0, 0xac, 0x8a, 0xba,
	0x08, 0xce, 0xe0, 0xe0, 0x79, 0x7a, 0x5d, 0x45, 0xd5, 0x1d, 0x0a, 0xc0, 0xae, 0x8b, 0x32, 0x8d,
	0x37, 0xdb, 0xa8, 0xdc, 0xa4, 0x09, 0xf5, 0xb5, 0x85, 0xbe, 0x34, 0xf0, 0x8c, 0x83, 0x2f, 0xa2,
	0xf2, 0x3c, 0xa1, 0xc1, 0x25, 0x98, 0x57, 0xd2, 0x44, 0x0e, 0x8c, 0xd3, 0xc4, 0xd7, 0x16, 0xda,
	0xd2, 0xc0, 0xe3, 0x34, 0x41, 0x6f, 0xc2, 0x84, 0xbb, 0xfa, 0xe3, 0x85, 0xb6, 0x9c, 0xad, 0xa6,
	0x21, 0xf7, 0xc4, 0x02, 0x44, 0x4f, 0xc0, 0x4c, 0xf3, 0x4d, 0x5d, 0x45, 0xf4, 0x95, 0xaf, 0x2f,
	0xb4, 0xa5, 0x89, 0x0f, 0xd2, 0xfc, 0x8a, 0x99, 0xc1, 0x9f, 0x1a, 0x4c, 0xb8, 0x2f, 0x5a, 0xc0,
	0xbc, 0x5b, 0x82, 0x0c, 0x0e, 0x6d, 0x05, 0x32, 0xe9, 0xb8, 0x49, 0x7a, 0x0a, 0x93, 0x3c, 0xda,
	0x12, 0xea, 0xeb, 0x0b, 0x7d, 0x39, 0x5b, 0x4d, 0xc2, 0x6f, 0xa2, 0x2d, 0xc1, 0x02, 0x43, 0x67,
	0x30, 0x2b, 0xe2, 0x78, 0x57, 0x55, 0x24, 0x8f, 0x09, 0xf5, 0x0d, 0xee, 0x32, 0x0b, 0x2f, 0x1a,
	0x0c, 0x77, 0xcf, 0x59, 0x89, 0xec, 0x1e, 0xef, 0x7d, 0xc2, 0x7b, 0x3f, 0x60, 0xf6, 0x79, 0x42,
	0xd1, 0xbb, 0xe0, 0xb4, 0x9e, 0xdc, 0x61, 0xca, 0x1d, 0xec, 0x16, 0x65, 0xf4, 0xbc, 0x06, 0x83,
	0xe5, 0xdf, 0xa3, 0x8f, 0x53, 0xb0, 0xca, 0xa8, 0x22, 0x79, 0xbd, 0x69, 0xda, 0x31, 0x05, 0xd0,
	0x34, 0xa9, 0x37, 0x4d, 0x1e, 0xc3, 0xe4, 0xa7, 0x28, 0xdb, 0x11, 0xdf, 0x58, 0x68, 0x4b, 0x0b,
	0x0b, 0x23, 0xb8, 0x05, 0x68, 0x3b, 0xf9, 0x7f, 0x52, 0xfe, 0xa5, 0x81, 0x71, 0x5e, 0x93, 0x2d,
	0x7a, 0x07, 0x0e, 0x32, 0x21, 0x1b, 0x9e, 0x68, 0xb6, 0x32, 0x43, 0x29, 0xa3, 0xf5, 0x08, 0xab,
	0x23, 0xb4, 0x04, 0xab, 0xa9, 0x49, 0xaa, 0xc2, 0x0a, 0x95, 0x7e, 0xd6, 0x23, 0x6c, 0xaa, 0xea,
	0xd0, 0x5b, 0x4a, 0x3b, 0x7a, 0x57, 0x3b, 0xeb, 0x91, 0x52, 0xcf, 0x29, 0x18, 0x6c, 0x14, 0xbc,
	0x1a, 0x35, 0xe5, 0xf5, 0x08, 0x73, 0x10, 0x9d, 0x01, 0xb4, 0x63, 0xf0, 0xa7, 0xdc, 0xa5, 0x3b,
	0xe5, 0xf5, 0x08, 0x77, 0x1c, 0xbe, 0x00, 0x30, 0x69, 0x49, 0xe2, 0xf4, 0x26, 0x8d, 0x83, 0x1f,
	0x61, 0xf6, 0xbc, 0x88, 0x12, 0x4c, 0x6e, 0x77, 0x84, 0xd6, 0x8f, 0xd0, 0xdf, 0x7b, 0x60, 0xa5,
	0x35, 0xd9, 0x6e, 0xea, 0xbb, 0x92, 0xf0, 0xe2, 0x9d, 0x95, 0x15, 0x32, 0x8a, 0xae, 0xee, 0x4a,
	0x82, 0xcd, 0x54, 0xfe, 0x0a, 0xde, 0x87, 0xb9, 0x48, 0x44, 0xcb, 0x22, 0xa7, 0x04, 0x3d, 0x01,
	0x83, 0x9d, 0x49, 0xf6, 0x26, 0xfc, 0x0a, 0xe6, 0x50, 0xf0, 0x0c, 0xec, 0x4b, 0x12, 0x55, 0xf1,
	0x2b, 0x55, 0xd5, 0x1e, 0x0f, 0x13, 0x21, 0x30, 0xea, 0xed, 0x6d, 0xc6, 0x2b, 0xb3, 0x30, 0xff,
	0x1d, 0x7c, 0x0f, 0x8e, 0x0a, 0x24, 0xb3, 0x9e, 0xc2, 0x84, 0xa5, 0x10, 0x11, 0x9a, 0xb4, 0x02,
	0x63, 0x23, 0x8f, 0x8b, 0x5d, 0x5e, 0xcb, 0xee, 0x84, 0x81, 0x4e, 0x60, 0x5a, 0xdc, 0xdc, 0x50,
	0x52, 0x4b, 0x71, 0x48, 0x2b, 0xf8, 0x19, 0xe6, 0xdf, 0xee, 0x48, 0x75, 0xa7, 0x8a, 0xfc, 0x00,
	0xec, 0xac, 0x88, 0x92, 0x4d, 0x25, 0x6c, 0x95, 0x62, 0x1e, 0x76, 0xf8, 0xc5, 0xf3, 0xac, 0x35,
	0x28, 0xfa, 0x18, 0x5c, 0xca, 0xeb, 0x6b, 0x2f, 0x8d, 0xf9, 0x25, 0x27, 0xec, 0x11, 0x80, 0x1d,
	0xda, 0x35, 0x69, 0xf0, 0x8b, 0x06, 0xb6, 0x4c, 0x2e, 0x1b, 0xfb, 0x08, 0x1c, 0x99, 0x5d, 0x00,
	0x2a, 0xbd, 0x1d, 0x76, 0x59, 0xc7, 0x76, 0xd6, 0xb1, 0x28, 0xfa, 0x04, 0xbc, 0xa6, 0x00, 0x75,
	0x4f, 0x54, 0xe0, 0x86, 0x7d, 0xe6, 0xb0, 0x4b, 0x7b, 0x36, 0x0d, 0x28, 0xb8, 0x5f, 0x56, 0x24,
	0xaa, 0xd3, 0x22, 0xdf, 0x5f, 0x3d, 0x27, 0x30, 0x15, 0x2f, 0x4e, 0x72, 0x2c, 0xad, 0xbd, 0x55,
	0xf4, 0x87, 0x06, 0xe8, 0x65, 0x99, 0x44, 0x35, 0xb9, 0xa8, 0x12, 0x52, 0x3d, 0x5e, 0xb6, 0x4b,
	0xb0, 0x0a, 0x16, 0x21, 0xba, 0xce, 0xc4, 0xa3, 0x72, 0x56, 0x10, 0x5e, 0x28, 0x04, 0xb7, 0x87,
	0xe8, 0x6d, 0x98, 0xd1, 0x2a, 0xde, 0xa4, 0x79, 0x92, 0xb2, 0x1d, 0xca, 0xf6, 0xa2, 0x8d, 0x81,
	0x56, 0xf1, 0xb9, 0x40, 0x98, 0x43, 0x42, 0xeb, 0xc6, 0x61, 0x2a, 0x1c, 0x12, 0x5a, 0x4b, 0x87,
	0xe0, 0xd7, 0xa6, 0xe8, 0xef, 0xd8, 0x12, 0xf9, 0xcf, 0xdf, 0xda, 0x3f, 0xec, 0xae, 0x1f, 0xc0,
	0x11, 0x55, 0x34, 0xa2, 0x79, 0x78, 0x05, 0xea, 0xd5, 0xea, 0xf7, 0x5f, 0xed, 0x6b, 0x70, 0xbf,
	0x22, 0x19, 0x79, 0x98, 0x1e, 0x1e, 0xbb, 0x4d, 0x32, 0xf0, 0xda, 0x64, 0x8f, 0xee, 0x66, 0xdf,
	0x6c, 0xbf, 0x8d, 0xc1, 0x7d, 0xb1, 0xab, 0x7b, 0x5a, 0xff, 0x14, 0x0e, 0x63, 0x29, 0xff, 0xe1,
	0x93, 0xf7, 0xc2, 0xc1, 0xc3, 0xc0, 0x5e, 0xdc, 0x07, 0x28, 0x7a, 0x06, 0x6f, 0xec, 0xf8, 0x30,
	0x36, 0x5c, 0x69, 0xc3, 0x05, 0x70, 0x14, 0xde, 0x57, 0x39, 0x3e, 0xda, 0xdd, 0xc3, 0xba, 0x81,
	0xf8, 0x94, 0xdb, 0x40, 0x7a, 0x2f, 0x50, 0x57, 0x79, 0x2a, 0x50, 0x17, 0xa3, 0xac, 0xa1, 0x44,
	0x52, 0xda, 0x06, 0x31, 0x64, 0x43, 0x83, 0xc9, 0x62, 0x2f, 0xe9, 0x03, 0x34, 0xf8, 0x7d, 0x0c,
	0x5e, 0xcb, 0x91, 0x1c, 0xc9, 0x67, 0x80, 0x3a, 0x24, 0xf5, 0x37, 0x93, 0x1b, 0xf6, 0xd5, 0x88,
	0x0f, 0x5b, 0x92, 0xd4, 0x7e, 0xfa, 0x1a, 0x4e, 0x06, 0x2c, 0x0d, 0xb7, 0xd4, 0x20, 0xc6, 0x71,
	0x8f, 0xa2, 0xfb, 0x61, 0x14, 0x47, 0x2a, 0x8c, 0xfe, 0xaf, 0x61, 0x24, 0x41, 0x2a, 0xcc, 0xe7,
	0x80, 0x3a, 0x0c, 0xa9, 0x10, 0x82, 0xa2, 0xc3, 0x70, 0xa8, 0x47, 0x7c, 0x98, 0x0c, 0x10, 0xfa,
	0x94, 0x82, 0xa9, 0xe4, 0x85, 0x8e, 0xc0, 0x7d, 0x99, 0xcb, 0xff, 0x61, 0x92, 0x30, 0xd8, 0x1b,
	0x21, 0x17, 0x66, 0xf2, 0x33, 0x82, 0x03, 0x1a, 0xf2, 0x60, 0xae, 0xbe, 0x17, 0x38, 0x32, 0x46,
	0x36, 0x58, 0x1c, 0xe1, 0xa6, 0x8e, 0xe6, 0x60, 0xb2, 0x6f, 0x01, 0x6e, 0x19, 0x08, 0x81, 0xd3,
	0xfe, 0xed, 0x73, 0x6c, 0xfa, 0xf4, 0x12, 0xac, 0x66, 0xb1, 0x21, 0x1f, 0x8e, 0x1b, 0xa3, 0x93,
	0xde, 0x1b, 0xf1, 0xab, 0xea, 0x84, 0x45, 0xa4, 0x9e, 0xd6, 0xf3, 0x6e, 0xe3, 0x52, 0x6f, 0x7c,
	0x3d, 0xe5, 0x5f, 0xcf, 0x1f, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x2d, 0xd5, 0xeb, 0x49,
	0x0b, 0x00, 0x00,
}
