// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Name struct {
	ID          string   `json:"id"`
	Identifiers []string `json:"identifiers"`
	Value       string   `json:"value"`
	Parent      *Topic   `json:"parent"`
	Scope       []*Topic `json:"scope"`
	Type        *Topic   `json:"type"`
}

type Occurrence struct {
	ID          string   `json:"id"`
	Identifiers []string `json:"identifiers"`
	Value       string   `json:"value"`
	Datatype    *Topic   `json:"datatype"`
	Parent      *Topic   `json:"parent"`
	Scope       []*Topic `json:"scope"`
	Type        *Topic   `json:"type"`
}

type Topic struct {
	ID                 string        `json:"id"`
	Identifiers        []string      `json:"identifiers"`
	SubjectIdentifiers []string      `json:"subject_identifiers"`
	SubjectLocators    []string      `json:"subject_locators"`
	Names              []*Name       `json:"names"`
	Occurrences        []*Occurrence `json:"occurrences"`
	Parent             *TopicMap     `json:"parent"`
}

type TopicMap struct {
	ID          string   `json:"id"`
	Identifiers []string `json:"identifiers"`
	Reifier     *Topic   `json:"reifier"`
}
