name: nm_delta
description: Generic data models for the Note Maps project.
version: 0.2.0
homepage: https://github.com/google/note-maps
publish_to: 'none'

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  quill_delta: ^3.0.0-nullsafety.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
