// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.0
// source: notes.proto

package notespb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_New       Status = 0
	Status_Created   Status = 1
	Status_Archived  Status = 2
	Status_Discarded Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "New",
		1: "Created",
		2: "Archived",
		3: "Discarded",
	}
	Status_value = map[string]int32{
		"New":       0,
		"Created":   1,
		"Archived":  2,
		"Discarded": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_notes_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_notes_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{0}
}

type Subject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Subject) Reset() {
	*x = Subject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{0}
}

func (x *Subject) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject    *Subject        `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Types      []*Subject      `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	Supertypes []*Subject      `protobuf:"bytes,3,rep,name=supertypes,proto3" json:"supertypes,omitempty"`
	Indicators []string        `protobuf:"bytes,4,rep,name=indicators,proto3" json:"indicators,omitempty"`
	Locators   []string        `protobuf:"bytes,5,rep,name=locators,proto3" json:"locators,omitempty"`
	Value      *Info_Value     `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Contents   []*Info_Content `protobuf:"bytes,7,rep,name=contents,proto3" json:"contents,omitempty"`
	Status     Status          `protobuf:"varint,8,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{1}
}

func (x *Info) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Info) GetTypes() []*Subject {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Info) GetSupertypes() []*Subject {
	if x != nil {
		return x.Supertypes
	}
	return nil
}

func (x *Info) GetIndicators() []string {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *Info) GetLocators() []string {
	if x != nil {
		return x.Locators
	}
	return nil
}

func (x *Info) GetValue() *Info_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Info) GetContents() []*Info_Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Info) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_New
}

type Info_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lexical  string   `protobuf:"bytes,1,opt,name=lexical,proto3" json:"lexical,omitempty"`
	Datatype *Subject `protobuf:"bytes,2,opt,name=datatype,proto3" json:"datatype,omitempty"`
}

func (x *Info_Value) Reset() {
	*x = Info_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info_Value) ProtoMessage() {}

func (x *Info_Value) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info_Value.ProtoReflect.Descriptor instead.
func (*Info_Value) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Info_Value) GetLexical() string {
	if x != nil {
		return x.Lexical
	}
	return ""
}

func (x *Info_Value) GetDatatype() *Subject {
	if x != nil {
		return x.Datatype
	}
	return nil
}

type Info_Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   *Subject `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Player *Subject `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *Info_Role) Reset() {
	*x = Info_Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info_Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info_Role) ProtoMessage() {}

func (x *Info_Role) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info_Role.ProtoReflect.Descriptor instead.
func (*Info_Role) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Info_Role) GetType() *Subject {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Info_Role) GetPlayer() *Subject {
	if x != nil {
		return x.Player
	}
	return nil
}

type Info_RolePlayed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        *Subject `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Association *Subject `protobuf:"bytes,2,opt,name=association,proto3" json:"association,omitempty"`
}

func (x *Info_RolePlayed) Reset() {
	*x = Info_RolePlayed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info_RolePlayed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info_RolePlayed) ProtoMessage() {}

func (x *Info_RolePlayed) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info_RolePlayed.ProtoReflect.Descriptor instead.
func (*Info_RolePlayed) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Info_RolePlayed) GetType() *Subject {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Info_RolePlayed) GetAssociation() *Subject {
	if x != nil {
		return x.Association
	}
	return nil
}

type Info_Content struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*Info_Content_Property
	//	*Info_Content_Role
	//	*Info_Content_RolePlayed
	Content isInfo_Content_Content `protobuf_oneof:"content"`
}

func (x *Info_Content) Reset() {
	*x = Info_Content{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info_Content) ProtoMessage() {}

func (x *Info_Content) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info_Content.ProtoReflect.Descriptor instead.
func (*Info_Content) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{1, 3}
}

func (m *Info_Content) GetContent() isInfo_Content_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Info_Content) GetProperty() *Subject {
	if x, ok := x.GetContent().(*Info_Content_Property); ok {
		return x.Property
	}
	return nil
}

func (x *Info_Content) GetRole() *Info_Role {
	if x, ok := x.GetContent().(*Info_Content_Role); ok {
		return x.Role
	}
	return nil
}

func (x *Info_Content) GetRolePlayed() *Info_RolePlayed {
	if x, ok := x.GetContent().(*Info_Content_RolePlayed); ok {
		return x.RolePlayed
	}
	return nil
}

type isInfo_Content_Content interface {
	isInfo_Content_Content()
}

type Info_Content_Property struct {
	Property *Subject `protobuf:"bytes,1,opt,name=property,proto3,oneof"`
}

type Info_Content_Role struct {
	Role *Info_Role `protobuf:"bytes,2,opt,name=role,proto3,oneof"`
}

type Info_Content_RolePlayed struct {
	RolePlayed *Info_RolePlayed `protobuf:"bytes,3,opt,name=role_played,json=rolePlayed,proto3,oneof"`
}

func (*Info_Content_Property) isInfo_Content_Content() {}

func (*Info_Content_Role) isInfo_Content_Content() {}

func (*Info_Content_RolePlayed) isInfo_Content_Content() {}

var File_notes_proto protoreflect.FileDescriptor

var file_notes_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a,
	0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x9e, 0x05, 0x0a, 0x04, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x22, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0a, 0x73, 0x75, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x65, 0x72, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x29,
	0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x47, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x78, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x65, 0x78, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x24, 0x0a,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x74,
	0x79, 0x70, 0x65, 0x1a, 0x46, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x56, 0x0a, 0x0a, 0x52,
	0x6f, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x93, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x26, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x42, 0x09,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2a, 0x3b, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x77, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x63, 0x61,
	0x72, 0x64, 0x65, 0x64, 0x10, 0x03, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x6e, 0x6f, 0x74, 0x65,
	0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notes_proto_rawDescOnce sync.Once
	file_notes_proto_rawDescData = file_notes_proto_rawDesc
)

func file_notes_proto_rawDescGZIP() []byte {
	file_notes_proto_rawDescOnce.Do(func() {
		file_notes_proto_rawDescData = protoimpl.X.CompressGZIP(file_notes_proto_rawDescData)
	})
	return file_notes_proto_rawDescData
}

var file_notes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notes_proto_goTypes = []interface{}{
	(Status)(0),             // 0: Status
	(*Subject)(nil),         // 1: Subject
	(*Info)(nil),            // 2: Info
	(*Info_Value)(nil),      // 3: Info.Value
	(*Info_Role)(nil),       // 4: Info.Role
	(*Info_RolePlayed)(nil), // 5: Info.RolePlayed
	(*Info_Content)(nil),    // 6: Info.Content
}
var file_notes_proto_depIdxs = []int32{
	1,  // 0: Info.subject:type_name -> Subject
	1,  // 1: Info.types:type_name -> Subject
	1,  // 2: Info.supertypes:type_name -> Subject
	3,  // 3: Info.value:type_name -> Info.Value
	6,  // 4: Info.contents:type_name -> Info.Content
	0,  // 5: Info.status:type_name -> Status
	1,  // 6: Info.Value.datatype:type_name -> Subject
	1,  // 7: Info.Role.type:type_name -> Subject
	1,  // 8: Info.Role.player:type_name -> Subject
	1,  // 9: Info.RolePlayed.type:type_name -> Subject
	1,  // 10: Info.RolePlayed.association:type_name -> Subject
	1,  // 11: Info.Content.property:type_name -> Subject
	4,  // 12: Info.Content.role:type_name -> Info.Role
	5,  // 13: Info.Content.role_played:type_name -> Info.RolePlayed
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_notes_proto_init() }
func file_notes_proto_init() {
	if File_notes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info_Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info_RolePlayed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info_Content); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_notes_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Info_Content_Property)(nil),
		(*Info_Content_Role)(nil),
		(*Info_Content_RolePlayed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notes_proto_goTypes,
		DependencyIndexes: file_notes_proto_depIdxs,
		EnumInfos:         file_notes_proto_enumTypes,
		MessageInfos:      file_notes_proto_msgTypes,
	}.Build()
	File_notes_proto = out.File
	file_notes_proto_rawDesc = nil
	file_notes_proto_goTypes = nil
	file_notes_proto_depIdxs = nil
}
