// Code generated by "kvschema"; DO NOT EDIT.

package docs

import (
	"github.com/google/note-maps/kv"
)

// Txn provides entities, components, and indexes backed by a key-value
// store.
//
// Usage:
//
//   d, err := Txn{Txn: txn}.DocumentComponent(0).Scan([]kv.Entity{7, 42})
//
type Txn struct {
	kv.Txn
	partition kv.Entity
}

// Partition returns the Entity that is used as a partition for all operations.
func (s Txn) Partition() kv.Entity {
	return s.partition
}

// WithPartition returns a new Txn with e as the partition for all operations.
func (s Txn) WithPartition(e kv.Entity) *Txn {
	s.partition = e
	return &s
}

// SetDocument sets the Document associated with e to v.
//
// Corresponding indexes are updated.
func (s *Txn) SetDocument(e kv.Entity, v *Document) error {
	key := make(kv.Prefix, 8+2+8)
	s.partition.EncodeAt(key)
	DocumentPrefix.EncodeAt(key[8:])
	e.EncodeAt(key[10:])
	var old Document
	if err := s.Get(key, old.Decode); err != nil {
		return err
	}
	if err := s.Set(key, v.Encode()); err != nil {
		return err
	}
	lek := len(key)
	kv.Entity(0).EncodeAt(key[10:])
	key = append(key, kv.Component(0).Encode()...)
	var (
		lik = len(key)
		es  kv.EntitySlice
	)

	// Update Title index
	key = key[:lek].AppendComponent(TitlePrefix)
	for _, iv := range old.IndexTitle() {
		key = append(key[:lik], iv.Encode()...)
		if err := s.Get(key, es.Decode); err != nil {
			return err
		}
		if es.Remove(e) {
			if err := s.Set(key, es.Encode()); err != nil {
				return err
			}
		}
	}
	for _, iv := range v.IndexTitle() {
		key = append(key[:lik], iv.Encode()...)
		if err := s.Get(key, es.Decode); err != nil {
			return err
		}
		if es.Insert(e) {
			if err := s.Set(key, es.Encode()); err != nil {
				return err
			}
		}
	}
	return nil
}

// GetDocument returns the Document associated with e.
//
// If no Document has been explicitly set for e, and GetDocument will return
// the result of decoding a Document from an empty slice of bytes.
func (s *Txn) GetDocument(e kv.Entity) (Document, error) {
	var v Document
	vs, err := s.GetDocumentSlice([]kv.Entity{e})
	if len(vs) >= 1 {
		v = vs[0]
	}
	return v, err
}

// GetDocumentSlice returns a Document for each entity in es.
//
// If no Document has been explicitly set for an entity, and the result will
// be a Document that has been decoded from an empty slice of bytes.
func (s *Txn) GetDocumentSlice(es []kv.Entity) ([]Document, error) {
	result := make([]Document, len(es))
	key := make(kv.Prefix, 8+2+8)
	s.partition.EncodeAt(key)
	DocumentPrefix.EncodeAt(key[8:])
	for i, e := range es {
		e.EncodeAt(key[10:])
		err := s.Get(key, (&result[i]).Decode)
		if err != nil {
			return nil, err
		}
	}
	return result, nil
}

// AllDocumentEntities returns the first n entities that have a Document, beginning
// with the first entity greater than or equal to *start.
//
// A nil start value will be interpreted as a pointer to zero.
//
// A value of n less than or equal to zero will be interpretted as the largest
// possible value.
func (s *Txn) AllDocumentEntities(start *kv.Entity, n int) (es []kv.Entity, err error) {
	prefix := make(kv.Prefix, 8+2)
	s.partition.EncodeAt(prefix)
	DocumentPrefix.EncodeAt(prefix[8:])
	iter := s.PrefixIterator(prefix[:10])
	defer iter.Discard()
	var actualStart kv.Entity
	if start == nil || *start == 0 {
		actualStart = 1
	} else {
		actualStart = *start
	}
	bstart := actualStart.Encode()
	for iter.Seek(bstart); iter.Valid() && (n <= 0 || len(es) < n); iter.Next() {
		var e kv.Entity
		e.Decode(iter.Key())
		es = append(es, e)
	}
	if start != nil && len(es) > 0 {
		*start = es[len(es)-1] + 1
	}
	return
}

// EntitiesMatchingDocumentTitle returns entities with Document values that return a matching kv.String from their IndexTitle method.
//
// The returned EntitySlice is already sorted.
func (s *Txn) EntitiesMatchingDocumentTitle(v kv.String) (kv.EntitySlice, error) {
	key := make(kv.Prefix, 8+2+8+2)
	s.partition.EncodeAt(key)
	DocumentPrefix.EncodeAt(key[8:])
	kv.Entity(0).EncodeAt(key[10:])
	TitlePrefix.EncodeAt(key[18:])
	key = append(key, v.Encode()...)
	var es kv.EntitySlice
	return es, s.Get(key, es.Decode)
}

// EntitiesByDocumentTitle returns entities with
// Document values ordered by the kv.String values from their
// IndexTitle method.
//
// Reading begins at cursor, and ends when the length of the returned Entity
// slice is less than n. When reading is not complete, cursor is updated such
// that using it in a subequent call to ByTitle would return next n
// entities.
func (s *Txn) EntitiesByDocumentTitle(cursor *kv.IndexCursor, n int) (es []kv.Entity, err error) {
	key := make(kv.Prefix, 8+2+8+2)
	s.partition.EncodeAt(key)
	DocumentPrefix.EncodeAt(key[8:])
	kv.Entity(0).EncodeAt(key[10:])
	TitlePrefix.EncodeAt(key[18:])
	iter := s.PrefixIterator(key)
	defer iter.Discard()
	iter.Seek(cursor.Key)
	if !iter.Valid() {
		return
	}
	var buf kv.EntitySlice
	if err = iter.Value(buf.Decode); err != nil {
		return
	}
	if cursor.Offset < len(buf) {
		es = append(es, buf[cursor.Offset:]...)
		if len(es) >= n {
			cursor.Offset += n
			if len(es) > n {
				es = es[:n]
			}
			return
		}
	}
	for iter.Next(); iter.Valid(); iter.Next() {
		if err = iter.Value(buf.Decode); err != nil {
			return
		}
		es = append(es, buf...)
		cursor.Key = append(cursor.Key[0:0], iter.Key()...)
		if len(es) >= n {
			cursor.Offset = len(buf) - (len(es) - n)
			if len(es) > n {
				es = es[:n]
			}
			return
		}
	}
	cursor.Offset = len(buf)
	return
}
