name: nix-build
on: [ pull_request push release ]
env:
  NIXPKGS_ALLOW_UNFREE: 1
jobs:
  build:
    runs-on: ubuntu-21.10
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: note-maps
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix build
