name: pull_request
on: [ ]
env:
  NIXPKGS_ALLOW_UNFREE: 1
jobs:
  build-preview:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: note-maps
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix shell -c make -e download DEBUG=
    - run: nix shell -c make -e build DEBUG=
    - uses: actions/upload-artifact@v2
      with:
        name: result
        path: ./out/
  deploy-preview:
    needs:
    - build-preview
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/download-artifact@master
      with:
        name: result
        path: ./out/
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: hosting:channel:deploy "$GITHUB_SHA"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: note-maps
        PROJECT_PATH: ./build/firebase/
