name: pull_request
on: pull_request
env:
  NIXPKGS_ALLOW_UNFREE: 1
jobs:
  build-preview:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: note-maps
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix-shell --run "make -e download DEBUG="
    - run: nix-shell --run "make -e build DEBUG="
    - uses: actions/upload-artifact@v2
      with:
        name: result
        path: ./out/
  deploy-preview:
    needs:
    - build-preview
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: result
        path: ./out/
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: hosting:channel:deploy "$GITHUB_SHA"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: note-maps
        PROJECT_PATH: ./build/firebase/
